// Curated subset of the real knowledge base (520 nodes / 117 scenarios)
// Selected to cover every variant the design must handle.

window.KB_META = {
  last_indexed: "2026-04-30",
  node_count: 520,
  scenario_count: 117,
  status_counts: { 現行: 515, 部分修正: 0, 已廢止: 5 },
  review_level_counts: { 人工: 39, 自動初校: 481 },
  category_counts: {
    國內旅費: 84,
    國外旅費: 71,
    出席費鐘點費: 38,
    特別費: 22,
    教育訓練費: 31,
    禮品交際費: 18,
    支出憑證與結報: 96,
    採購: 47,
    其他通則: 113,
  },
};

window.KB_PARENTS = [
  "國內旅費", "國外旅費", "支出憑證與結報", "出席費鐘點費",
  "教育訓練費", "禮品交際費", "特別費", "採購", "其他通則",
];

window.KB_NODES = [
  {
    id: "A-國內旅費-005",
    type: "核心法規",
    parent: "國內旅費",
    title: "第五條 交通費上限",
    tags: ["交通費", "報支上限", "必要路程", "覈實報支"],
    summary: "交通費以機關所在地與出差地為起訖點,按必要路程覈實報支。搭乘飛機、高鐵、商務艙等需檢附票根,惟當日往返或經費結報系統報支者免附。自駕汽車每公里3元、機車每公里2元,不得另報油料、過路費。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "人工",
    version: "2024-01-15",
    source: "law.dgbas.gov.tw",
    source_url: "https://law.dgbas.gov.tw/LawContent.aspx?id=FL017584",
  },
  {
    id: "A-國內旅費-009",
    type: "核心法規",
    parent: "國內旅費",
    title: "第九條 住宿費報支",
    tags: ["住宿費", "60公里", "事前核准", "覈實報支"],
    summary: "出差地距機關所在地 60 公里以上者,得報住宿費。距離未滿 60 公里者,原則不得報支住宿費,但因業務需要、事前經機關核准且確有住宿事實者,例外得報。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "人工",
    version: "2024-01-15",
    source: "law.dgbas.gov.tw",
    source_url: "https://law.dgbas.gov.tw/LawContent.aspx?id=FL017584",
  },
  {
    id: "A-國內旅費-004",
    type: "核心法規",
    parent: "國內旅費",
    title: "第四條 出差報支程序",
    tags: ["公差派遣", "十五日內", "報支期限", "憑證審核"],
    summary: "出差事畢之報支程序:十五日內檢具附表二「出差旅費報告表」連同憑證書據,報請機關審核。十五日為期限,逾期之處理由機關權責認定。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "人工",
    version: "2024-01-15",
    source: "law.dgbas.gov.tw",
    certainty: "inferred",
    no_inference_note: "此情形依機關權責或實務認定,本站僅彙整法規條文,實際結果以主計室認定為準。",
  },
  {
    id: "A-國內旅費-011",
    type: "核心法規",
    parent: "國內旅費",
    title: "第十一條 長期出差遞減",
    tags: ["長期出差", "8折", "7折", "1個月", "2個月"],
    summary: "在同一地點出差超過 1 個月、未滿 2 個月部分,住宿費按 8 折報支;2 個月以上部分,按 7 折報支。遞減基準依平日/假日上限分別計算。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "人工",
    version: "2024-01-15",
    source: "law.dgbas.gov.tw",
    source_url: "https://law.dgbas.gov.tw/LawContent.aspx?id=FL017584",
  },
  {
    id: "A-國外旅費-007",
    type: "核心法規",
    parent: "國外旅費",
    title: "第七條 國外日支生活費",
    tags: ["日支生活費", "國外旅費", "美元", "百分率"],
    summary: "國外出差日支生活費依「中央政府各機關派赴國外各地區出差人員生活費日支數額表」之規定報支。出差人員生活費日支數額按百分率計算,其總計後尾數不足一元者,進位為一元。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-26", review_level: "人工",
    version: "2026-01-01",
    source: "law.dgbas.gov.tw",
    source_url: "https://law.dgbas.gov.tw/LawContent.aspx?id=FL017584",
  },
  {
    id: "B-國內旅費-001",
    type: "支出標準",
    parent: "國內旅費",
    title: "附表一 各機關員工國內出差報支數額",
    tags: ["交通費", "住宿費", "雜費", "覈實報支"],
    summary: "各機關員工國內出差旅費報支數額表(2024-01-15 生效):住宿費平日上限 3,500 元、假日 4,500 元;雜費每日上限 400 元;交通費依職等覈實報支。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-27", review_level: "人工",
    version: "2024-01-15", source: "law.dgbas.gov.tw",
    rate_table: {
      caption: "附表一 各機關員工國內出差旅費報支數額表",
      unit: "新臺幣元", effective: "2024-01-15",
      headers: ["費別", "平日", "假日"],
      rows: [
        ["住宿費每日上限", "3,500", "4,500"],
        ["雜費每日上限", "400", "400"],
        ["交通費上限", "覈實報支", "覈實報支"],
      ],
    },
  },
  {
    id: "B-國外旅費-002",
    type: "支出標準",
    parent: "國外旅費",
    title: "大陸港澳出差生活費日支數額",
    tags: ["大陸港澳", "日支生活費", "美元"],
    summary: "中央政府各機關派赴大陸地區、香港及澳門出差人員生活費日支數額表(2026-01-01 生效)。列載 19 個城市與「其他」,單位:美元。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-27", review_level: "人工",
    version: "2026-01-01", source: "law.dgbas.gov.tw",
    rate_table: {
      caption: "大陸港澳出差生活費日支數額表",
      unit: "美元", effective: "2026-01-01", searchable: true,
      headers: ["城市", "日支數額"],
      rows: [
        ["北京 (Beijing)", 295], ["上海 (Shanghai)", 268], ["大連 (Dalian)", 195],
        ["濟南 (Jinan)", 236], ["青島 (Qingdao)", 202], ["武漢 (Wuhan)", 225],
        ["長沙 (Changsha)", 223], ["西安 (Xi'an)", 226], ["成都 (Chengdu)", 256],
        ["貴陽 (Guiyang)", 212], ["深圳 (Shenzhen)", 245], ["廣州 (Guangzhou)", 216],
        ["海口 (Haikou)", 225], ["杭州 (Hangzhou)", 214], ["三亞 (Sanya)", 218],
        ["廈門 (Xiamen)", 238], ["香港 (Hong Kong)", 339], ["澳門 (Macau)", 211],
        ["其他 (Other)", 194],
      ],
    },
  },
  {
    id: "B-國外旅費-003",
    type: "支出標準",
    parent: "國外旅費",
    title: "國外出差生活費日支數額表(全球)",
    tags: ["日支生活費", "國外旅費", "亞太", "歐洲", "北美"],
    summary: "派赴國外各地區出差人員生活費日支數額表。共 6 大區域、200 個國家、551 筆城市/「其他」費率。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-27", review_level: "人工",
    version: "2026-01-01", source: "law.dgbas.gov.tw",
    rate_table: {
      caption: "國外出差生活費日支數額表",
      unit: "美元", effective: "2026-01-01", searchable: true, sectioned: true,
      headers: ["國家", "城市", "數額"],
      sections: [
        { title: "亞太地區", rows: [
          ["日本 (Japan)", "東京 (Tokyo)", 299],
          ["日本 (Japan)", "大阪 (Osaka)", 246],
          ["日本 (Japan)", "京都 (Kyoto)", 282],
          ["日本 (Japan)", "其他 (Other)", 209],
          ["南韓 (Korea)", "首爾 (Seoul)", 290],
          ["南韓 (Korea)", "濟州 (Cheju)", 321],
          ["新加坡 (Singapore)", "新加坡", 452],
          ["泰國 (Thailand)", "曼谷 (Bangkok)", 284],
          ["馬來西亞 (Malaysia)", "吉隆坡 (Kuala Lumpur)", 251],
          ["澳大利亞 (Australia)", "雪梨 (Sydney)", 304],
        ]},
        { title: "歐洲地區", rows: [
          ["英國 (UK)", "倫敦 (London)", 411],
          ["法國 (France)", "巴黎 (Paris)", 372],
          ["德國 (Germany)", "柏林 (Berlin)", 268],
          ["瑞士 (Switzerland)", "蘇黎世 (Zurich)", 419],
          ["荷蘭 (Netherlands)", "阿姆斯特丹 (Amsterdam)", 332],
        ]},
        { title: "北美洲地區", rows: [
          ["美國 (USA)", "紐約 (New York)", 462],
          ["美國 (USA)", "華盛頓 (Washington D.C.)", 397],
          ["美國 (USA)", "舊金山 (San Francisco)", 423],
          ["加拿大 (Canada)", "多倫多 (Toronto)", 295],
        ]},
      ],
    },
  },
  {
    id: "A-國外旅費-024",
    type: "核心法規",
    parent: "國外旅費",
    title: "派外進修/研究/實習人員生活費月支標準",
    tags: ["月支生活費", "派外進修", "級距", "國外旅費"],
    summary: "派赴國外進修、研究、實習人員停留 31 日以上者改按月支生活費(美元/月),依日支數額級距對應 8 級。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-27", review_level: "人工",
    version: "2024-01-15", source: "law.dgbas.gov.tw",
    rate_table: {
      caption: "月支生活費級距表",
      unit: "美元/月", effective: "2024-01-15", sectioned: true,
      sections: [
        { title: "月支生活費", headers: ["日支數額級距(美元)", "月支生活費(美元)"], rows: [
          ["410 以上", "1,700"], ["370–409", "1,600"], ["330–369", "1,500"], ["290–329", "1,400"],
          ["250–289", "1,300"], ["210–249", "1,200"], ["170–209", "1,100"], ["169 以下", "1,000"],
        ]},
      ],
      notes: [
        "出國 1~15 日按日支表全額;16~30 日每日為日支表 1/20",
        "31 日起按月支表;畸零日按月支表 1/30",
        "供膳宿者 3 折、供宿不供膳 4 折、供膳不供宿 9 折",
      ],
    },
  },
  {
    id: "B-國外旅費-006",
    type: "支出標準",
    parent: "國外旅費",
    title: "國外出差人員旅行平安保險費",
    tags: ["保險費", "國外旅費", "美元", "天數"],
    summary: "外交部所訂之國外出差人員旅行平安保險費標準,依出差天數與地區別計算保險費(美元)。",
    status: "現行", agency: "外交部", reviewed: "2026-04-27", review_level: "人工",
    version: "2025-07-01", source: "mofa.gov.tw",
    rate_table: { lookup_type: "insurance" },
  },
  {
    id: "B-國外旅費-007",
    type: "支出標準",
    parent: "國外旅費",
    title: "舊版國外出差日支數額(已廢止)",
    tags: ["日支生活費", "已廢止", "歷史保留"],
    summary: "本表已於 2026-01-01 為新版日支數額表所取代,僅供歷史比對使用。出差期間跨越新舊規定者,依各自期間適用。",
    status: "已廢止", agency: "行政院主計總處", reviewed: "2026-04-26", review_level: "人工",
    version: "2024-01-15", source: "law.dgbas.gov.tw",
    effective_period: "2024-01-15 ~ 2025-12-31",
    superseded_by: "B-國外旅費-003",
  },
  {
    id: "C-國內旅費-004",
    type: "解釋函令",
    parent: "國內旅費",
    title: "通勤距離得否報支住宿費釋疑",
    tags: ["住宿費", "60公里", "通勤", "釋疑"],
    summary: "主計總處 113 年 3 月 18 日函釋:出差地與機關所在地距離未滿 60 公里,如因業務需要連續多日無法當日往返者,得敘明事由報經機關核准後支給住宿費。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "人工",
    version: "2024-03-18", source: "dgbas.gov.tw",
  },
  {
    id: "C-國外旅費-012",
    type: "解釋函令",
    parent: "國外旅費",
    title: "未列載城市之日支數額適用",
    tags: ["未列載城市", "其他", "日支生活費"],
    summary: "派赴本表未列載之城市出差,按該國「其他」欄之數額支給;若該國亦未列載者,按該區域「其他」支給。內蒙古地區比照「其他」支給。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-26", review_level: "自動初校",
    version: "2024-09-01", source: "dgbas.gov.tw",
  },
  {
    id: "D-支出憑證與結報-033",
    type: "問答集",
    parent: "支出憑證與結報",
    title: "Q33 採購簽案核准是否須正本",
    tags: ["原始憑證", "採購", "簽案", "影本"],
    summary: "採購案經費報支時,核准簽案毋須為正本,因簽案非屬政府支出憑證處理要點所定收據類憑證,影本即可。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-25", review_level: "自動初校",
    version: "2024-01-01", source: "dgbas.gov.tw",
    certainty: "contested",
    no_inference_note: "此情形實務見解不一或法規未明確規範,本站不提供判斷,請逕洽主計室確認。",
  },
  {
    id: "D-國內旅費-001",
    type: "問答集",
    parent: "國內旅費",
    title: "Q1 出差超過 30 天之住宿費如何遞減",
    tags: ["住宿費", "長期出差", "遞減", "8折"],
    summary: "在同一地點出差超過 1 個月、未滿 2 個月部分按 8 折,2 個月以上按 7 折。遞減基準仍為平日 3,500 / 假日 4,500。",
    status: "現行", agency: "行政院主計總處(成大適用版)", reviewed: "2026-04-25", review_level: "自動初校",
    version: "2024-01-01", source: "dgbas.gov.tw",
  },
  {
    id: "D-國內旅費-006",
    type: "問答集",
    parent: "國內旅費",
    title: "Q6 商務艙票根遺失是否仍可報支",
    tags: ["商務艙", "票根", "遺失", "證明"],
    summary: "搭乘商務艙者,票根或購票證明文件原則須附;若遺失,得以航空公司或售票機構出具之搭乘證明替代,並敘明事由。",
    status: "現行", agency: "行政院主計總處(成大適用版)", reviewed: "2026-04-25", review_level: "自動初校",
    version: "2024-01-01", source: "dgbas.gov.tw",
  },
  {
    id: "D-國內旅費-009",
    type: "問答集",
    parent: "國內旅費",
    title: "Q9 自駕公里數如何計算",
    tags: ["自駕", "公里數", "必要路程", "地圖"],
    summary: "汽機車自駕公里數由各機關自行核處,得參考 Google Maps 等地圖軟體建議之最短路徑或常用路徑,作為必要路程之依據。",
    status: "現行", agency: "行政院主計總處(成大適用版)", reviewed: "2026-04-25", review_level: "自動初校",
    version: "2024-01-01", source: "dgbas.gov.tw",
  },
  {
    id: "D-出席費鐘點費-014",
    type: "問答集",
    parent: "出席費鐘點費",
    title: "Q14 內聘講座鐘點費上限",
    tags: ["鐘點費", "內聘", "外聘", "上限"],
    summary: "機關內部人員擔任講座之鐘點費,每小時上限 1,000 元;外聘專家學者每小時上限 2,000 元;國際知名學者得上提至 4,000 元。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-26", review_level: "自動初校",
    version: "2023-08-01", source: "dgbas.gov.tw",
  },
  {
    id: "D-禮品交際費-008",
    type: "問答集",
    parent: "禮品交際費",
    title: "Q8 公務禮品價值上限",
    tags: ["禮品", "交際費", "上限", "首長"],
    summary: "一般公務禮品每件以新臺幣 2,000 元為上限;贈送外賓或具重要紀念意義者,得依機關首長核定上提,惟須敘明事由。",
    status: "現行", agency: "行政院主計總處", reviewed: "2026-04-26", review_level: "自動初校",
    version: "2024-06-01", source: "dgbas.gov.tw",
  },
];

window.KB_SCENARIOS = [
  {
    id: "day-trip",
    title: "當日往返出差",
    subtitle: "不過夜,只報交通費",
    parent: "國內旅費", expense: "交通費",
    primary_ids: ["A-國內旅費-005", "B-國內旅費-001", "D-國內旅費-001"],
    tags: ["交通費", "報支上限", "覈實報支"],
    attachments: [
      "車票/票根 或 高鐵/火車購票證明",
      "出差行程表 / 派令",
      "若使用經費結報系統:無須檢附票根",
    ],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "overnight",
    title: "跨夜住宿",
    subtitle: "需報住宿費,平日 3,500 假日 4,500 上限",
    parent: "國內旅費", expense: "住宿費",
    primary_ids: ["A-國內旅費-009", "A-國內旅費-011", "B-國內旅費-001", "D-國內旅費-001"],
    tags: ["住宿費", "覈實報支"],
    attachments: [
      "住宿發票或收據",
      "出差行程表 / 派令",
      "若 < 60 公里:事前機關核准之簽呈",
    ],
    approvers: ["出差人員填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
    flow: {
      start: "distance",
      questions: {
        distance: {
          label: "出差地距機關所在地是否 ≥ 60 公里?",
          options: [
            { label: "≥ 60 公里(一般情況)", next: "weekday" },
            { label: "< 60 公里(例外)", conclude: "under60" },
          ],
        },
        weekday: {
          label: "投宿日是平日還是假日?",
          hint: "假日含放假日前一天,不含放假日最後一天。",
          options: [
            { label: "平日", next: "long_stay_wk" },
            { label: "假日", next: "long_stay_hd" },
          ],
        },
        long_stay_wk: {
          label: "在同一地點出差是否超過 1 個月?",
          options: [
            { label: "未滿 1 個月", conclude: "wk_normal" },
            { label: "1 ~ 2 個月部分", conclude: "wk_long_8" },
            { label: "2 個月以上部分", conclude: "wk_long_7" },
          ],
        },
        long_stay_hd: {
          label: "在同一地點出差是否超過 1 個月?",
          options: [
            { label: "未滿 1 個月", conclude: "hd_normal" },
            { label: "1 ~ 2 個月部分", conclude: "hd_long_8" },
            { label: "2 個月以上部分", conclude: "hd_long_7" },
          ],
        },
      },
      conclusions: {
        under60: { title: "< 60 公里 — 原則不得報支住宿費", limit: "—",
          note: "因業務需要、事前經機關核准且確有住宿事實者,得依例外辦理。",
          refs: ["A-國內旅費-009"] },
        wk_normal: { title: "平日,1 個月內 — 可報住宿費", limit: "上限 3,500 元/夜",
          refs: ["A-國內旅費-009", "B-國內旅費-001"] },
        wk_long_8: { title: "平日,1~2 個月部分 — 8 折", limit: "上限 2,800 元/夜",
          refs: ["A-國內旅費-009", "A-國內旅費-011", "B-國內旅費-001"] },
        wk_long_7: { title: "平日,2 個月以上 — 7 折", limit: "上限 2,450 元/夜",
          refs: ["A-國內旅費-009", "A-國內旅費-011", "B-國內旅費-001"] },
        hd_normal: { title: "假日,1 個月內 — 可報住宿費", limit: "上限 4,500 元/夜",
          refs: ["A-國內旅費-009", "B-國內旅費-001"] },
        hd_long_8: { title: "假日,1~2 個月部分 — 8 折", limit: "上限 3,600 元/夜",
          refs: ["A-國內旅費-009", "A-國內旅費-011", "B-國內旅費-001"] },
        hd_long_7: { title: "假日,2 個月以上 — 7 折", limit: "上限 3,150 元/夜",
          refs: ["A-國內旅費-009", "A-國內旅費-011", "B-國內旅費-001"] },
      },
    },
  },
  {
    id: "premium-class",
    title: "搭高鐵或飛機艙等",
    subtitle: "商務艙限部會首長以上",
    parent: "國內旅費", expense: "交通費",
    primary_ids: ["A-國內旅費-005", "B-國內旅費-001", "D-國內旅費-006"],
    tags: ["商務車廂", "經濟艙", "艙等", "票根"],
    attachments: ["票根或購票證明", "出差行程表 / 派令", "搭商務艙者:身份證明或核准文件"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "self-drive",
    title: "自駕汽機車出差",
    subtitle: "汽車 3 元/公里、機車 2 元/公里",
    parent: "國內旅費", expense: "交通費",
    primary_ids: ["A-國內旅費-005", "D-國內旅費-009"],
    tags: ["自駕", "公里數", "必要路程"],
    attachments: ["出差行程表(含公里數)", "公里數計算依據", "車輛行照影本"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "from-home",
    title: "由居住地直接出發",
    subtitle: "起訖點以機關所在地計算上限",
    parent: "國內旅費", expense: "通則",
    primary_ids: ["A-國內旅費-005", "D-國內旅費-001"],
    tags: ["機關所在地", "誠信原則"],
    attachments: ["出差行程表(註明居住地)", "車票/票根", "覈實報支實付金額"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "necessary-distance",
    title: "必要路程怎麼算",
    subtitle: "由各機關自行核處公里數",
    parent: "國內旅費", expense: "交通費",
    primary_ids: ["A-國內旅費-005", "D-國內旅費-009"],
    tags: ["必要路程", "公里數"],
    attachments: ["地圖軟體截圖", "出差行程表", "機關內規(若有)"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "overseas-asia",
    title: "亞太地區出差",
    subtitle: "日支生活費依城市,以美元計",
    parent: "國外旅費", expense: "日支生活費",
    primary_ids: ["A-國外旅費-007", "B-國外旅費-003"],
    tags: ["國外旅費", "日支生活費", "亞太"],
    attachments: ["護照影本", "登機證", "出國行程表", "外幣兌換證明"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "overseas-other-city",
    title: "未列載城市出差",
    subtitle: "按該國或該區域之「其他」支給",
    parent: "國外旅費", expense: "日支生活費",
    primary_ids: ["B-國外旅費-003", "C-國外旅費-012"],
    tags: ["未列載城市", "其他", "日支生活費"],
    attachments: ["護照影本", "城市無列載證明", "出國行程表"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "overseas-insurance",
    title: "國外平安保險費",
    subtitle: "外交部標準,依天數與地區",
    parent: "國外旅費", expense: "保險費",
    primary_ids: ["B-國外旅費-006"],
    tags: ["保險費", "外交部"],
    attachments: ["保險單據", "出國行程表"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "lecture-internal",
    title: "內聘講座鐘點費",
    subtitle: "機關內部人員,每小時 1,000 元",
    parent: "出席費鐘點費", expense: "鐘點費",
    primary_ids: ["D-出席費鐘點費-014"],
    tags: ["鐘點費", "內聘"],
    attachments: ["講座簽到表", "課程表", "領據"],
    approvers: ["承辦單位核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "lecture-external",
    title: "外聘講座鐘點費",
    subtitle: "外聘專家,每小時 2,000 元",
    parent: "出席費鐘點費", expense: "鐘點費",
    primary_ids: ["D-出席費鐘點費-014"],
    tags: ["鐘點費", "外聘"],
    attachments: ["講座簽到表", "課程表", "領據", "講者學經歷"],
    approvers: ["承辦單位核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "gift-general",
    title: "公務禮品贈送",
    subtitle: "每件 2,000 元上限,外賓得上提",
    parent: "禮品交際費", expense: "禮品",
    primary_ids: ["D-禮品交際費-008"],
    tags: ["禮品", "交際費"],
    attachments: ["禮品清冊", "受贈對象", "首長核定簽呈"],
    approvers: ["承辦單位核章", "主辦會計核章", "機關首長核定"],
  },
  {
    id: "procurement-copy",
    title: "採購簽案影本可否",
    subtitle: "簽案非憑證,影本即可",
    parent: "支出憑證與結報", expense: "結報",
    primary_ids: ["D-支出憑證與結報-033"],
    tags: ["原始憑證", "採購", "影本"],
    attachments: ["簽案影本", "驗收紀錄", "原始憑證"],
    approvers: ["承辦單位核章", "主辦會計核章"],
  },
  {
    id: "late-submission",
    title: "逾 15 日結報",
    subtitle: "由機關權責認定處理",
    parent: "支出憑證與結報", expense: "結報",
    primary_ids: ["A-國內旅費-004"],
    tags: ["十五日內", "逾期", "權責"],
    attachments: ["逾期事由說明", "出差旅費報告表", "原始憑證"],
    approvers: ["申請人填表", "單位主管核章", "主辦會計核章", "機關首長核定"],
  },
];
